# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 
  config.vm.define "server" do |c|
    c.vm.box = "bento/ubuntu-18.04"
    c.vm.synced_folder "./scripts", "/scripts"
    c.vm.provider "hyperv" do |v|
      v.memory = 4098
      v.cpus = 1
    end
    c.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
    end
  end
  
end
