# Setting up Postgres and Axon Server
# Execute: docker-compose -p GAME_HOSTING_SERVICES up -d
#
# Setting up AWX
# Read: https://grantlittle.me/index.php/2020/06/08/installing-ansible-awx-on-windows-using-wsl-2-docker-desktop/
#
# Quick Commands:
# 1. wsl
# 2. cd ~
# 3. cd installer
# 4. ansible-playbook -i inventory install.yml
version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Password1
      - POSTGRES_DB=GameHosting
  pgAdmin4:
    image: dpage/pgadmin4:5.5
    container_name: pgAdmin4
    restart: always
    ports:
      - 8989:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Password1
  axon-server:
    image: axoniq/axonserver:4.5
    container_name: axon-server
    restart: always
    ports:
      - 8024:8024
      - 8124:8124
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true