# Setting up MSSQL and Axon Server
# Execute: docker-compose -p GAME_HOSTING_SERVICES up -d
#
# Setting up AWX
# Read: https://grantlittle.me/index.php/2020/06/08/installing-ansible-awx-on-windows-using-wsl-2-docker-desktop/
#
# Quick Commands:
# 1. wsl
# 2. cd ~
# 3. cd installer
# 4. ansible-playbook -i inventory install.yml
version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    restart: always
    ports:
      - 8024:8024
      - 8124:8124
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true