package com.example.demo.ovh.instance.entity;

public enum InstanceStatus {
        ACTIVE,
        BUILDING,
        DELETED,
        DELETING,
        ERROR,
        HARD_REBOOT,
        PASSWORD,
        PAUSED,
        REBOOT,
        REBUILD,
        RESCUED,
        RESIZED,
        REVERT_RESIZE,
        SOFT_DELETED,
        STOPPED,
        SUSPENDED,
        UNKNOWN,
        VERIFY_RESIZE,
        MIGRATING,
        RESIZE,
        BUILD,
        SHUTOFF,
        RESCUE,
        SHELVED,
        SHELVED_OFFLOADED,
        RESCUING,
        UNRESCUING,
        SNAPSHOTTING,
        RESUMING,
}
